name: DressUp Style AI
description: Discover your digital wardrobe and personal stylist. DressUp Style AI creates fashion-perfect outfits based on your clothes, weather, and mood — helping you make smarter, more sustainable style choices every day.
full_description: '<b>v1.2.2 (Nov 7, 2025)</b><br>
<br>- You can now rearrange the clothes inside your outfit.
<br>- After taking a photo, you can crop only the part containing the clothing item.
<br>- You can now change clothing colors after uploading.
<br>- Visual improvements across the app.
<br>- Various bug fixes and performance enhancements.'
android: https://play.google.com/store/apps/details?id=com.daniele.dressup
iOS: https://apps.apple.com/app/dressup-style-ai/id6746646997
web: false
screenshots:
  - 01-screenshot.png
  - 02-screenshot.png
  - 03-screenshot.png
  - 04-screenshot.png
  - 05-screenshot.png
  - 06-screenshot.png
  - 07-screenshot.png
  - 08-screenshot.png
  - 09-screenshot.png
producthunt: false
#companies:
#  - url: https://telegra.ph/Replace-this-link-07-23
#    image: androidpolice.png
#  - url: https://telegra.ph/Replace-this-link-07-23
#    image: producthunt.png
